name: myComOrg1 Hello

on:
  push:
    branches: [ $default-branch ]
  pull-request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout

      - name: Run a one-line script
        run: echo Hello from myComOrg1

