name: sample-1

on:
  repository_dispatch:
    types: [org-workflow-bot]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Run a one-line script
        run: echo Hello from myComOrg1 sample-1 workflow
